### ISSUE TITLE
Data Driven doesn't load tests 

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-connectors-azure#10]
![image](https://user-images.githubusercontent.com/70174048/102027226-5a61e880-3dab-11eb-8a92-c2d24af3ea66.png)
![image](https://user-images.githubusercontent.com/70174048/102027241-82514c00-3dab-11eb-918c-09b9355c7699.png)
![Uploading image.png…]()

**Comment by YanivAroch** [comment]
![Uploading image.png…]()

**Comment by gravity-api** [comment]
Looks like a TFS issue. If there is no value, Rhino cannot extract it.
Make sure TFS is properly parsing the parameters.
